### ISSUE TITLE
Is there any chance of MacOS port?

### ISSUE THREAD

**Issue by Azarattum** [houmain/keymapper#13]
A MacOS port would be truly great! Especially one supporting Apple Silicon processors. I'm fairly new to this field and don't have much experience with Mac development...

**Comment by dumblob** [comment]
@Azarattum did you find some solution?

**Comment by Azarattum** [comment]
@dumblob I'm currently using `yabai` on MacOS which isn't that great but gets the job done.

**Comment by houmain** [comment]
This is finally available for testing! Currently in the `next` branch. 

If you want to try it out, please follow these [installation instructions](https://github.com/houmain/keymapper/tree/next#macos).

**Note that it currently cannot run next to the latest [Karabiner-Elements](https://karabiner-elements.pqrs.org/) (which you might be using), because keymapper depends on a newer version of the [Karabiner-DriverKit-VirtualHIDDevice](https://github.com/pqrs-org/Karabiner-DriverKit-VirtualHIDDevice)**.

**Comment by houmain** [comment]
This is now in the `main` branch. I reverted the [Karabiner-DriverKit-VirtualHIDDevice](https://github.com/pqrs-org/Karabiner-DriverKit-VirtualHIDDevice) to version 2.1.0, the one which the current Karabiner-Elements release version 14.12.0 is using.
