### ISSUE TITLE
How can I run keymapperd automatically when start ubuntu 24 os

### ISSUE THREAD

**Issue by harrytran998** [houmain/keymapper#142]
Thank for great product <3. 
When I read the docs -- `sudo systemctl enable keymapperd` Here is the only way to enable service, but when I ran this command, `keymapperd` not starting, only `sudo systemctl start keymapperd \n keymapper` worked.

Do anyone know I miss something? Thank you.

**Comment by houmain** [comment]
Hi, thanks!
Did you add `keymapper` to the desktop environment's auto-started applications? Both `keymapper` and `keymapperd` need to run.
I think I could also automatically create that when installing the package...

**Comment by ristomatti** [comment]
@houmain At least on my system, `keymapper` by default starts automatically based on the `/etc/xdg/autostart/keymapper.desktop` file. I am certain of this as I had to resort to Arch wiki to find out how to disable it without touching the file, so that it would not interfere with my systemd user script to start it . 🙂
