### ISSUE TITLE
Fake ALT >> CONTROL remap. 

### ISSUE THREAD

**Issue by miron2363** [houmain/keymapper#154]
I use the left alt as a control.

Then I assign control + j/k/h/l to the arrows and expect that when I physically press alt left +j/k/h/l it will be treated as control + j/k/h/l and activate arrow keys due to the fact that I assigned left alt as Control. 

This is how it works in powertoys and I expected the same behavior, because now when I physically press alt+h/j/k/l it doesn't activate the arrows. Is there a way to achieve the desired behavior?

![image](https://github.com/houmain/keymapper/assets/80050619/495d21f6-5e5f-473e-92ea-1d9283f65750)

**Comment by ristomatti** [comment]
I also got confused with this in the beginning. I suggest reading the [functional principle](https://github.com/houmain/keymapper#keymapperctl) section from the README a few times. It can save a lot of time later on.

The input keys should in this case correspond to the actual physical keys as the mappings done earlier in the config won't apply to the ones following(*). 

Just changing `Control` to `AltLeft` on the hjkl mappings would likely do the trick. 

*) This used to be always the case prior to Keymapper 4.4.0 which introduced support for multiple stage processing. I have not yet experimented with the feature but I believe it could be used to achieve a solution that could perhaps be more intuitive for you. If you wish to try it, add this before the hjkl mappings:

```
[stage]
# HJKL mappings here
```

P.S. Please use a code block formatting instead of a screenshot so it's easy to just copy and test.

![Screenshot_20240704_152920_Opera](https://github.com/houmain/keymapper/assets/9029939/b2be403a-b04d-4083-b8ce-1c5737a4e710)

**Comment by miron2363** [comment]
Thanks! That works!

```
AltLeft >> Control

[stage]
Control{J} >> ArrowDown
Control{K} >> ArrowUp
Control{H} >> ArrowLeft
Control{L} >> ArrowRight`
```
