### ISSUE TITLE
Context not shifting

### ISSUE THREAD

**Issue by kbilsted** [houmain/keymapper#162]
how does the context switching behave?

Below is a few modes, normal and insert. it works fine, but since i have a plugin in visualstudio i think most of these definitions should be deactivated. I made a mode for `devenv.exe` and it triggers the mode fine. But leaving visual studio by switching to another window does not have a desired effect of going into any of the other contexts. not even the default one.

I possibly will have other applications, maybe browsers that have better inbuilt support via plugins. so devenv.exe may not be the only thing to be excluded.

 

```
# Script for https://github.com/houmain/keymapper
Shift >> Shift
ControlLeft  >> ControlLeft

# Virtual modifiers
NORMALMODE = Virtual1
INSERTMODE = Virtual2
STATE_FILE = c:/temp/keymapper.state
Log_FILE = c:/temp/keymapper.log
state      = $(echo $0 > STATE_FILE) $(echo $0 >> Log_FILE)
TO_INSERT  = !NORMALMODE INSERTMODE  						
TO_NORMAL  = !INSERTMODE  NORMALMODE   						



[modifier = "NORMALMODE" title="Chrome"]
(Shift X)	    >> (Shift ControlLeft){T}
X 			    >> ControlLeft{W}
T 			    >> ControlLeft{T} TO_INSERT
...

[modifier = "NORMALMODE"]
ContextActive   >> state["NORMAL"]
(Shift A)	    >> End TO_INSERT
...

[modifier = "INSERTMODE"]
ContextActive   >> state["INSERT"]  
(J K) 		    >> TO_NORMAL
AltLeft{H}	    >> ArrowLeft
...

[path="devenv.exe"] # Visual studio
ContextActive  >> state["App: VS"] 
...

[default]
Q{W}            >> ControlLeft{F4}                  # quit Window
ContextActive   >> state["Default"] TO_INSERT
...
```

**Comment by ristomatti** [comment]
A suggestion: try to reduce the example/repro configs to be as simplified as possible and to be be more specific what you're expecting to happen and what actually happens. I realize @houmain can somehow decipher and get the gist of the issue most of the times, but I'd have to spend quite a bit of time to come up with a config to test this without the surrounding context and what to observe.

I do remember hitting some unexpected (or misunderstood) behaviour when attempting to mimic Vim style modality myself. I've since deleted the attempts and do not remember what exactly the issues where though...

**Comment by houmain** [comment]
I am not sure if I understood you correctly but more than one context can be active at once. 
Try moving the visual studio context up an append `Any >> Any` so the other contexts get skipped
```
[path="devenv.exe"] # Visual studio
ContextActive  >> state["App: VS"] 
Any >> Any
```
BTW. questions how things work are better suited in the [discussions](https://github.com/houmain/keymapper/discussions/categories/q-a) than the issues section.
