### ISSUE TITLE
Keypresses not properly passed to Arc Browser on windows

### ISSUE THREAD

**Issue by rp1231** [houmain/keymapper#190]
This is the config that I'm using
```
[path = "Arc.exe"]
CapsLock{L} >> Control{Alt{ArrowUp}}
CapsLock{H} >> Control{Alt{ArrowDown}}
```
But it works only on pressed the keycombination multiple times.

It's a little baffling because my similar remaps for other browsers work flawlessly.

**Comment by houmain** [comment]
I wanted to try it out, but it does not even start without registration...

**Comment by ristomatti** [comment]
@rp1231 Isn't Arc based on Chromium? Do you see the same issue also on Chromium (or Chrome, Edge, Brave or other Chromium based ones)?

**Comment by ristomatti** [comment]
I noticed there's a different how `CapsLock` is mapped on Windows as well (might be due to running in a VM though). On Linux, if I map `CapsLock >> ControlLeft`, even the CapsLock light stops coming up, but on Windows it went on/off, even though CapsLock itself didn't turn on. This was also on global mappings.

**Comment by ristomatti** [comment]
I noticed it's a bit inconsistent as well. Repeatedly hitting the shortcut seemed to improve the consistency, but I didn't test if the seemingly improved consistency disappears after a while.

What I would do instead is to try using a different key as the mod. E.g. Alt, Tab or the ` key.
