### ISSUE TITLE
Permissive hold?

### ISSUE THREAD

**Issue by marek-g** [houmain/keymapper#210]
Is it possible to distinguish between permissive hold (https://precondition.github.io/home-row-mods#permissive-hold) and hold on other key-press (https://precondition.github.io/home-row-mods#hold-on-other-key-press)?

I tired:

```ini
A{B} >> C
```

```ini
(A B) >> C
```

```ini
A B >> C
```

```ini
A B !B !A >> C
```

and I receive C for both cases: permissive hold & other-key press.

I don't want to use timeouts. They don't solve the problem, too and are giving me too many false positives for my typing style.

Thank you again for your great software and I wish you Happy New Year!

**Comment by houmain** [comment]
Does this do what you want?

```
A{B !B} >> C
``` 

> Thank you again for your great software and I wish you Happy New Year!

Thank you very much! I also wish you a Happy New Year!

**Comment by marek-g** [comment]
Great! It works!!

But it was not easy to figure out my case. I wanted space to act as a space when tap and as a 2 steps modifier when hold. First step is to select row-mods combination (S - Alt, D - Shift, F - Ctrl). Second step is to keep them sticky when released while keeping the modifier pressed. And the modifier should work with permissive hold & other-key press, so it is a space when i quickly type a text...

The final fully working code is:

```ini
Modifiers = Space
ModifiersSelected = Virtual31
AltLock = Virtual32
ShiftLock = Virtual33
CtrlLock = Virtual34
WinLock = Virtual35

[modifier="!ModifiersSelected"]
Modifiers{(S D F G) !S} >> AltLock ShiftLock CtrlLock WinLock ^ ModifiersSelected
Modifiers{(S D F) !S} >> AltLock ShiftLock CtrlLock ^ ModifiersSelected
Modifiers{(S D G) !S} >> AltLock ShiftLock WinLock ^ ModifiersSelected
Modifiers{(D F G) !D} >> ShiftLock CtrlLock WinLock ^ ModifiersSelected
Modifiers{(S D) !S} >> AltLock ShiftLock ^ ModifiersSelected
Modifiers{(S F) !S} >> AltLock CtrlLock ^ ModifiersSelected
Modifiers{(S G) !S} >> AltLock WinLock ^ ModifiersSelected
Modifiers{(D F) !D} >> ShiftLock CtrlLock ^ kModifiersSelected
Modifiers{(D F) !D} >> ShiftLock CtrlLock ^ ModifiersSelected
Modifiers{(D G) !D} >> ShiftLock WinLock ^ ModifiersSelected
Modifiers{(F G) !F} >> CtrlLock WinLock ^ ModifiersSelected
Modifiers{S !S} >> AltLock ^ ModifiersSelected
Modifiers{D !D} >> ShiftLock ^ ModifiersSelected
Modifiers{F !F}>> CtrlLock ^ ModifiersSelected
Modifiers{G !G}>> WinLock ^ ModifiersSelected

[modifier="Modifiers"]
ContextActive >> ^ !ModifiersSelected !AltLock !ShiftLock !CtrlLock !WinLock
AltLock >> AltLeft
ShiftLock >> ShiftLeft
CtrlLock >> ControlLeft
WinLock >> MetaLeft
```

It is simpler when you don't want permissive hold & other-key press or if you have a dedicated, single purpose Modifiers key:

```ini
[modifier="Modifiers"]
ContextActive >> ^ !ModifiersSelected !AltLock !ShiftLock !CtrlLock !WinLock
AltLock >> AltLeft
ShiftLock >> ShiftLeft
CtrlLock >> ControlLeft
WinLock >> MetaLeft

[modifier="Modifiers !ModifiersSelected"]
S >> AltLock ^ ModifiersSelected
D >> ShiftLock ^ ModifiersSelected
F >> CtrlLock ^ ModifiersSelected
G >> WinLock ^ ModifiersSelected
```

Thank you Albert!

**Comment by ristomatti** [comment]
@marek-g I tried your config out of curiosity. I doubt I'd ever be able to wrap my head around to learning that but it was fun to try regardless. Thanks for sharing!

**Comment by marek-g** [comment]
Hi @ristomatti !

That's ok. Everyone has different needs and that's why keymapper exists.

My setup is not that hard to grasp. It is based on simple requirements:
- move everything useful to the letter keys
- use layer / modifier keys with thumbs
- be able to use it with split and normal keyboards - hence max. 3 thumb keys: LAlt, Space, RAlt (space can simulate 2 thumb keys)
- do not use time constants to avoid unexpected behavior, home row modifiers are possible but only while another key is pressed

So I have:
- an Extended key (on Caps Lock) - the same idea as in Albert's config - as a navigation layer. It has modifiers built in, but you cannot use them with latters
- RAlt - for Polish letters + all kinds od parenthesis
- LAlt - as a numbers / calculator / programming layer
- Modifiers layer - it is very similar in the idea to Extended key, but you can use it with letters and that's very useful for software like Emacs but not necessarily for Vim

Is it convenient? I don't know. It's a result of theoretical thinking and reading about other people setups for 3 months. I have that setup fully working for the first time now. I need to learn it. The great thing is it is almost not conflicting with standard keyboard way of usage,. If I forget that I'm using new setup, all ways to things usually also work.

![Keyboard](https://github.com/user-attachments/assets/25345261-5a1f-450a-b822-79d50ac8e144)

Configuration: https://marek-g.github.io/posts/hardware/keyboard/

P.S. I was learning how to use keymapper mostly from your setup. I think you have explored the configuration language to its limits. It was very inspiring! Your setup was one of the reasons I decided to stick with the keymapper, as I could see how powerful it can be.

**Comment by ristomatti** [comment]
Thanks for expanding! It's always interesting to read what others have done as often you get new ideas. I also noticed we share similar goals/interests in many ways but with a completely different approach. Also - I am familiar with the home row mods concept due to discovering QMK prior to Keymapper. In theory it makes a lot of sense but it somehow just feels too much brain gymnastics for me. I'm past 40 and it took me completely off guard how long it took for me to:

1. Switch from ThinkPad Compact Keyboards to my first mechanical one (Keychron K3 Pro ISO Nordic). ThinkPad keyboards have the left side mods arranged like `Fn Ctrl Win Alt`. For a long time I had got accustomed to configuring my most used shortcuts to use `Alt` rather than `Ctrl` as I could press it with my thumb. Initially I thought this should not be an issue as the K3 was programmable but to my surprise that didn't help much at all since the spacebar was so damn wide (like on basically every mechanical with the standard layout). Eventually I did come up with some remap that I was happy with, but the hunger grow and I decided to buy the K15 Pro US ANSI (Alice layout) model....

2. Adapting to the semi-split Alice layout and the US ANSI layout. I was already familiar the US layout since forever but it took SOOO MUCH fiddling to come up with my preferred way to typing the Finnish umlauts `ä` and `ö`. Adapting to the split layout was a lot easier but it too took non-insignificant amount of unlearning muscle memory (and now I can't properly type with a non-split laoyut anymore :smile:)

I don't remember how long it exactly took me to go through these two phases but it was months. The process thought me to stick to what I'm best at learning - new shortcuts. But now with the Alice layout keyboard I got the extra thumb button between the two space bars. Also, I had noticed I pretty much always typed space with my right thumb, so I was able to make the left space bar a modifier as well.

With lots of iterations, I have settled with using the extra middle button (originally `Fn`) as both `Esc` and `Alt`. Both space bars act as as `Space` and `Meta` (with the twist that the left one prioritizes `Meta` and the right one `Space`). For the umlauts, I've adapted to using `AltRight/AltGr` similarly as you have. I have also retained some `AltGr` combos from the ISO layout that just turned too difficult to unlearn like `AltGr+2` for `@`.

I've continued my old habit of customizing the keybindings for each application and barely use `Ctrl` at all (even though I've of course remapped it to `CapsLock`). I just try to do this in Keymapper instead rather than in the apps themselves (still not consistently though). Thumb modifiers have turned out to be the biggest ergonomic improvement for me. I've been eyeballing the Voyager keyboard for some time but I'm just not sure if I'm ready yet for true split (I'd love the additional thumb keys and the overall looks though!). :slightly_smiling_face: 

> P.S. I was learning how to use keymapper mostly from your setup. I think you have explored the configuration language to its limits. It was very inspiring! Your setup was one of the reasons I decided to stick with the keymapper, as I could see how powerful it can be.

Thanks for the kind words! It's been great fun exploring various ideas and I'm happy to hear making it public has had the effect I was hoping for it to have. 

P.S. I had tons of changes accumulated to my config but as somewhat of a git history purist, I've been postponing it to split the changes into smaller self contained commits. I just have not find the time to do that as I've been experimenting with a lot of things and it would not been easy to do that. Because of that, I made an exception and pushed a huge "WIP" commit that I hope to split later on. In case you're interested, see commit [21364b00](https://github.com/ristomatti/keymapper-config/commit/21364b00954ff1e1671eaad4a609a04b643bc55b). There's some new idea's I've come up IIRC. Not really documented in any way though...

**Comment by marek-g** [comment]
Hi @ristomatti! Thank you too for expanding!

I'm also in my 40s, but I regret that I didn't play with keyboard setups before. I always feared that I will not be able to use normal keyboard anymore. Maybe that's work from home that allowed me to think that there's nothing to worry about. And I am very positively surprised how good our brains are for adapting to the changes! But I'm not doing drastic changes (like I'm not even trying to change QWERTY to something else).

Thanks for showing me your latest changes! They remembered me that I wanted to try `scrcpy`. I thought it's only to capture the screen content, but I can see you can also redirect mouse and keyboard. Wow! That's amazing!

> Recently I've noticed more and more issues pop up which indicates to me the project is finally beginning to get the traction it deserves!

I hope so! It totally deserves it.

There were a few problems / bugs I encountered that made me think about looking for something else, but I realized everything else has far fewer features and it's better to stay and report bugs. And you and Albert are so responsive that I'm glad I've stayed.

(for example there is still a bug when you have multiple conditional sections like when I tried to embed multiple layouts in one file mixed with multiple devices - some statements can like leak between sections improperly and I lost lots of time on figuring out what's happening coming to conclusion there is a bug somewhere - probably I will report it - but it takes time to simplify the example and I am so short on my time - but there is almost always workaround - in this case I was able to execute 'keymapperctl --setconfig" when I want to switch layout, which is even easier to maintain solution anyway)

**Comment by houmain** [comment]
> I think Keymapper is a hidden gem that for some reason has been overshadowed by other similar tools with a different focus. Recently I've noticed more and more issues pop up which indicates to me the project is finally beginning to get the traction it deserves!

Thank you very much! Your words and continuous help are more rewarding than many stars and issue reports. :smile: 

> coming to conclusion there is a bug somewhere - probably I will report it - but it takes time to simplify the example and I am so short on my time
> but there is almost always workaround - in this case I was able to execute 'keymapperctl --setconfig" when I want to switch layout, which is even easier to maintain solution anyway)

Glad to hear, that you found a solution that works for you. I am grateful for any help to iron out sources of frustration.
